[tox]
envlist = py313, py314, black, check-manifest, flake8
isolated_build = true

[testenv]
deps =
    .
    pytest
    pytest-cov
commands =
    python -m pytest \
        --basetemp={envtmpdir} \
        --cov=mopidy_subidy --cov-report=term-missing \
        {posargs}

[testenv:black]
skip_install = true
deps =
    black
commands = python -m black --check .

[testenv:check-manifest]
deps =
    check-manifest
commands = python -m check_manifest

[testenv:flake8]
skip_install = true
deps =
    flake8
    flake8-bugbear
    flake8-import-order
commands = python -m flake8 --show-source --statistics
