version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

workflows:
  version: 2
  test:
    jobs:
      - py314
      - py313
      - black
      - check-manifest
      - flake8

jobs:
  py314: &test-template
    docker:
      - image: cimg/python:3.14
    steps:
      - checkout
      - restore_cache:
          name: Restoring tox cache
          key: tox-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "pyproject.toml" }}
      - run:
          name: Run tests
          command: |
            pip install tox
            tox -e $CIRCLE_JOB -- \
              --junit-xml=test-results/pytest/results.xml \
              --cov-report=xml
      - save_cache:
          name: Saving tox cache
          key: tox-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "pyproject.toml" }}
          paths:
            - ./.tox
            - ~/.cache/pip
      - codecov/upload:
          file: coverage.xml
      - store_test_results:
          path: test-results

  py313:
    <<: *test-template
    docker:
      - image: cimg/python:3.13

  black: *test-template

  check-manifest: *test-template

  flake8: *test-template
